cal/api/urls.py
from django.urls import path
from rest_framework import routers
from .views import EventViewSet, EventCategoryViewSet, IconViewSet, ColorViewSet, ProfileViewSet

router = routers.SimpleRouter()
router.register('events', EventViewSet, basename='events')
router.register('categories', EventCategoryViewSet, basename='categories')
router.register('icons', IconViewSet, basename='icons')
router.register('colors', ColorViewSet, basename='colors')
router.register('profiles', ProfileViewSet, basename='profiles')

urlpatterns = []
urlpatterns += router.urls

cal/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'cal'

urlpatterns = [
    url(r'^profile/', views.profile, name='profile_edit'),
    url(r'^calendar/month/$',
        login_required(views.CalendarViewMonth.as_view(), login_url='login'), name='calendar_month'),
    url(r'^calendar/3months/$',
        login_required(views.CalendarView3Months.as_view(), login_url='login'), name='calendar_3months'),
    url(r'^calendar/6months/$',
        login_required(views.CalendarView6Months.as_view(), login_url='login'), name='calendar_6months'),
    url(r'^calendar/year/$',
        login_required(views.CalendarViewYear.as_view(), login_url='login'), name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
]

djangocalendar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from cal import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cal.urls')),
    path('api/', include('cal.api.urls')),
]

urlpatterns += [
    path('', views.loginPage, name='login'),
    path('registration/', views.registerPage, name='registration'),
    path('logout/', views.logoutUser, name='logout'),
]

cal/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ObjectDoesNotExist
from django.utils.html import format_html
from django.urls import reverse


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    TEMPLATES = [
        ("table.css", "Таблица"),
        ("modern.css", "Современный"),
    ]
    template = models.CharField(max_length=30, choices=TEMPLATES, default="modern.css", verbose_name="Вид календаря")
    show_year = models.BooleanField(default=True, verbose_name="Показывать год")
    cross = models.BooleanField(default=True, verbose_name="Зачеркивание")

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    try:
        instance.profile.save()
    except ObjectDoesNotExist:
        Profile.objects.create(user=instance)


class EventCategory(models.Model):
    name = models.CharField(max_length=200)
    user = models.ForeignKey(User, blank=False, on_delete=models.CASCADE)
    # icon = models.ImageField()

    def __str__(self):
        return self.name


class Color(models.Model):
    GRAY = '757575'
    ORANGE = 'F2994A'
    YELLOW = 'F2C94C'
    GREEN = '00CCA7'
    BLUE = '2D9CDB'
    RED = 'EB5757'
    BLACK = '4F4F4F'
    COLORS = [
        (GRAY, 'gray'),
        (ORANGE, 'orange'),
        (YELLOW, 'yellow'),
        (GREEN, 'green'),
        (BLUE, 'blue'),
        (RED, 'red'),
        (BLACK, 'black')
    ]
    color = models.CharField(
        max_length=8,
        choices=COLORS,
        default=GRAY,
    )
    # name = models.CharField(max_length=12, default="gray")

    def __str__(self):
        return self.color


class Icon(models.Model):

    name = models.CharField(max_length=50)
    # icon = models.FileField(upload_to='icons/', blank=True, null=True)
    inline_svg = models.CharField(max_length=2000, blank=True)

    # def save(self, *args, **kwargs):
    #     if self.icon.name.endswith('.svg'):
    #         self.inline_svg = self.icon.read().decode('utf-8')
    #         super().save(*args, **kwargs)

    def __str__(self):
        return format_html(self.inline_svg + self.name)
        # return self.icon.url


class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    date_time = models.DateField()
    user = models.ForeignKey(User, blank=False, on_delete=models.CASCADE)
    notification_time = models.DateTimeField(blank=True, null=True)
    event_category = models.ForeignKey(EventCategory, null=True, blank=True, on_delete=models.SET_NULL)
    icon = models.ForeignKey(Icon, null=True, blank=True, on_delete=models.SET_NULL)
    event_color = models.ForeignKey(Color, null=True, default=1, on_delete=models.PROTECT, related_name="event_color")
    icon_color = models.ForeignKey(Color, null=True, default=None, on_delete=models.PROTECT, related_name="icon_color")

    @property
    def get_html_url(self):
        url = reverse('cal:event_edit', args=(self.id,))
        return f'<button data-target="#exampleModal" data-toggle="modal" data-id="{self.id}"> {self.title} </button>'

    def __str__(self):
        return self.title

cal/forms.py
from django.forms import ModelForm, DateInput
from .models import Event, Profile
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.contrib.auth.models import User


class EventForm(ModelForm):
    class Meta:
        model = Event
        # datetime-local is a HTML5 input type, format to make date time show on fields
        widgets = {
            'date_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
            'notification_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        }
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        # input_formats to parse HTML5 datetime-local input to datetime field
        self.fields['date_time'].input_formats = ('%Y-%m-%dT%H:%M',)
        self.fields['notification_time'].input_formats = ('%Y-%m-%dT%H:%M',)


class ProfileForm(ModelForm):

    class Meta:
        model = Profile
        fields = ('template', 'show_year', 'cross',)
        CHOICES = [("table.css", "Таблица"), ("modern.css", "Современный")]
        widgets = {
            'template': forms.RadioSelect(choices=CHOICES)
        }


class LoginUserForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

    def __init__(self, *args, **kwargs):
        super(LoginUserForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.TextInput(attrs={'placeholder': 'Логин'})
        self.fields['password'].widget = forms.PasswordInput(attrs={'placeholder': 'Введите пароль'})


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Логин'}),
            'email': forms.EmailInput(attrs={'placeholder': 'email@example.com'}),
        }

    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget = forms.PasswordInput(attrs={'placeholder': 'Введите пароль'})
        self.fields['password2'].widget = forms.PasswordInput(attrs={'placeholder': 'Подтвердите пароль'})

cal/api/views.py
from rest_framework import viewsets

from .serializers import EventSerializer, EventCategorySerializer, IconSerializer, ColorSerializer, ProfileSerializer
from ..models import Event, EventCategory, Icon, Color, Profile


class EventCategoryViewSet(viewsets.ModelViewSet):
    def get_queryset(self):
        user = self.request.user
        return EventCategory.objects.filter(user=user)
    serializer_class = EventCategorySerializer


class EventViewSet(viewsets.ModelViewSet):

    def get_queryset(self):
        user = self.request.user
        return Event.objects.filter(user=user)
    serializer_class = EventSerializer


class IconViewSet(viewsets.ModelViewSet):

    queryset = Icon.objects.all()
    serializer_class = IconSerializer


class ColorViewSet(viewsets.ModelViewSet):

    queryset = Color.objects.all()
    serializer_class = ColorSerializer


class ProfileViewSet(viewsets.ModelViewSet):
    def get_queryset(self):
        user = self.request.user
        return Profile.objects.filter(user=user)
    serializer_class = ProfileSerializer

cal/views.py
from datetime import datetime, timedelta, date
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, JsonResponse
from django.views import generic
from django.utils.safestring import mark_safe
# from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import calendar

from .models import *
from .utils import Yearcal
from .forms import EventForm, ProfileForm, CreateUserForm, LoginUserForm


class CalendarViewMonth(generic.ListView):
    model = Event
    template_name = 'cal/calendar_templates/calendar_month.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        initial_dict = {
            "template": self.request.user.profile.template,
            "show_year": self.request.user.profile.show_year,
            "cross": self.request.user.profile.cross,
        }
        d = get_date(self.request.GET.get('month', None))
        cal = Yearcal(d.year, d.month, self.request.user)
        html_cal = cal.formatcustomrow(theyear=d.year, start_month=d.month, length=1, rows=1)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        context['profile'] = ProfileForm(initial=initial_dict, instance=self.request.user.profile)
        return context


class CalendarView3Months(generic.ListView):
    model = Event
    template_name = 'cal/calendar_templates/calendar_3months.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        initial_dict = {
            "template": self.request.user.profile.template,
            "show_year": self.request.user.profile.show_year,
            "cross": self.request.user.profile.cross,
        }
        d = get_date(self.request.GET.get('month', None))
        cal = Yearcal(d.year, d.month, self.request.user)
        html_cal = cal.formatcustomrow(theyear=d.year, start_month=d.month, length=3, rows=1)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        context['profile'] = ProfileForm(initial=initial_dict, instance=self.request.user.profile)
        return context


class CalendarView6Months(generic.ListView):
    model = Event
    template_name = 'cal/calendar_templates/calendar_6months.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        initial_dict = {
            "template": self.request.user.profile.template,
            "show_year": self.request.user.profile.show_year,
            "cross": self.request.user.profile.cross,
        }
        d = get_date(self.request.GET.get('month', None))
        cal = Yearcal(d.year, d.month, self.request.user)
        html_cal = cal.formatcustomrow(theyear=d.year, start_month=d.month, length=6, rows=2)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        context['profile'] = ProfileForm(initial=initial_dict, instance=self.request.user.profile)
        return context


class CalendarViewYear(generic.ListView):
    model = Event
    template_name = 'cal/calendar_templates/calendar_year.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        initial_dict = {
            "template": self.request.user.profile.template,
            "show_year": self.request.user.profile.show_year,
            "cross": self.request.user.profile.cross,
        }
        d = get_date(self.request.GET.get('year', None))
        cal = Yearcal(d.year, d.month, self.request.user)
        html_cal = cal.formatcustomrow(d.year, start_month=1, length=12, rows=3)
        context['calendar'] = mark_safe(html_cal)
        context['prev_year'] = prev_year(d)
        context['next_year'] = next_year(d)
        context['profile'] = ProfileForm(initial=initial_dict, instance=self.request.user.profile)
        return context


def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()


def prev_month(d):
    first = d.replace(day=1)
    prev_m = first - timedelta(days=1)
    month = 'month=' + str(prev_m.year) + '-' + str(prev_m.month)
    return month


def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_m = last + timedelta(days=1)
    month = 'month=' + str(next_m.year) + '-' + str(next_m.month)
    return month


def prev_year(d):
    prev_y = d.replace(year=d.year - 1)
    year = 'year=' + str(prev_y.year) + '-' + str(prev_y.month)
    return year


def next_year(d):
    next_y = d.replace(year=d.year + 1)
    year = 'year=' + str(next_y.year) + '-' + str(next_y.month)
    return year


def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()


def event(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()

    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('cal:calendar'))
    return render(request, 'cal/event.html', {'form': form})


@login_required(login_url='login')
def profile(request):
    initial_dict = {
        "template": request.user.profile.template,
        "show_year": request.user.profile.show_year,
        "cross": request.user.profile.cross,
    }
    if request.method == "POST":
        form = ProfileForm(request.POST, instance=request.user.profile)
    else:
        form = ProfileForm(initial=initial_dict, instance=request.user.profile)
    if form.is_valid():
        form.save()
        # return HttpResponseRedirect(reverse('cal:calendar'))
        if 'calendar' in request.META.get('HTTP_REFERER'):
            return redirect(request.META.get('HTTP_REFERER'))
        else:
            redirect('calendar/year')


def loginPage(request):
    if request.user.is_authenticated:
        return redirect('calendar/year')
    else:
        form = LoginUserForm()
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('login')
            else:
                messages.info(request, "Неверный логин или пароль")
        context = {'form': form}
        return render(request, 'registration/login.html', context)


def registerPage(request):
    form = CreateUserForm()

    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, "Создан пользователь " + user)
            return redirect('login')

    context = {'form': form}
    return render(request, 'registration/registration.html', context)


def logoutUser(request):
    logout(request)
    return redirect('login')

cal/templates/cal/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"> -->
    <link rel="stylesheet" type="text/css" href="{% static '/cal/css/template.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/cal/css/header/header.css' %}">
    {% if request.user.profile.template == "modern.css" %}
    <link rel="stylesheet" type="text/css" href="{% static '/cal/css/modern.css' %}">
    {% endif %}
    {% if request.user.profile.template == "table.css" %}
    <link rel="stylesheet" type="text/css" href="{% static '/cal/css/table.css' %}">
    {% endif %}
    <title>Django Calendar App</title>
</head>
<body>
    {% include "cal/header.html" %}
    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!--  <script src="{% static 'cal/js/jquery-3.5.1.min' %}"></script>-->
    {% if user.is_authenticated %}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% endif %}
    {% block script %}
    {% endblock %}
</body>

</html>

cal/templates/cal/calendar_3months.html
{% extends 'cal/base.html' %}

{% block content %}
<div class="clearfix">
	<a class="btn btn-info left" href="{% url 'cal:calendar_3months' %}?{{ prev_month }}"> Previous Month </a>
	<a class="btn btn-info right" href="{% url 'cal:calendar_3months' %}?{{ next_month }}"> Next Month </a>
</div>

{{ calendar }}
{% endblock %}

{% block script %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'cal/css/3-months/styles.css' %}">
<script src="{% static 'cal/js/overlay.js' %}"></script>
<script src="{% static 'cal/js/jquery.ddslick.min.js' %}"></script>
 <link rel="stylesheet" type="text/css" href="{% static 'cal/css/3-months/overlay.css' %}">
 <script src="{% static 'cal/js/modal-form.js' %}"></script>

  {% endblock %}

cal/templates/cal/calendar_6months.html
{% extends 'cal/base.html' %}

{% block content %}
<div class="clearfix">
	<a class="btn btn-info left" href="{% url 'cal:calendar_6months' %}?{{ prev_month }}"> Previous Month </a>
	<a class="btn btn-info right" href="{% url 'cal:calendar_6months' %}?{{ next_month }}"> Next Month </a>
</div>

{{ calendar }}
{% endblock %}

{% block script %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'cal/css/3-months/styles.css' %}">
<script src="{% static 'cal/js/overlay.js' %}"></script>
<script src="{% static 'cal/js/jquery.ddslick.min.js' %}"></script>
 <link rel="stylesheet" type="text/css" href="{% static 'cal/css/3-months/overlay.css' %}">
 <script src="{% static 'cal/js/modal-form.js' %}"></script>

  {% endblock %}

cal/templates/cal/calendar_month.html
{% extends 'cal/base.html' %}

{% block content %}
<div class="clearfix">
	<a class="btn btn-info left" href="{% url 'cal:calendar_month' %}?{{ prev_month }}"> Previous Month </a>
	<a class="btn btn-info right" href="{% url 'cal:calendar_month' %}?{{ next_month }}"> Next Month </a>
</div>

{{ calendar }}
{% endblock %}


{% block script %}
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'cal/css/month/styles.css' %}">
<script src="{% static 'cal/js/overlay.js' %}"></script>
<script src="{% static 'cal/js/jquery.ddslick.min.js' %}"></script>
 <link rel="stylesheet" type="text/css" href="{% static 'cal/css/month/overlay.css' %}">
 <script src="{% static 'cal/js/modal-form.js' %}"></script>
 
  {% endblock %}

cal/templates/cal/header.html
<header>
  <div class="views-container">
      {%  url 'cal:calendar_month' as url_month %}
      <a class="view-type" href="{% url 'cal:calendar_month' %}">
          <svg width="44" height="44" viewBox="0 0 44 44" fill="none" xmlns="http://www.w3.org/2000/svg" {% if request.path == url_month %} class="active" {% endif %}>
              <path fill-rule="evenodd" clip-rule="evenodd" d="M3.66699 11V5.5H38.5003V11H3.66699ZM36.667 14.6667H5.50033C4.49199 14.6667 3.66699 15.4917 3.66699 16.5V27.5C3.66699 28.5083 4.49199 29.3333 5.50033 29.3333H36.667C37.6753 29.3333 38.5003 28.5083 38.5003 27.5V16.5C38.5003 15.4917 37.6753 14.6667 36.667 14.6667ZM3.66699 38.5H38.5003V33H3.66699V38.5Z" fill="#E0E0E0" />
          </svg>
      </a>
      {%  url 'cal:calendar_3months' as url_3months %}
      <a class="view-type" href="{% url 'cal:calendar_3months' %}">
          <svg width="50" height="50" viewBox="0 0 50 50" fill="none" xmlns="http://www.w3.org/2000/svg" {% if request.path == url_3months %} class="active" {% endif %}>
              <path fill-rule="evenodd" clip-rule="evenodd" d="M8.33398 37.5001H18.7507V10.4167H8.33398V37.5001ZM20.834 37.5001H31.2507V10.4167H20.834V37.5001ZM33.334 37.5001V10.4167H43.7506V37.5001H33.334Z" fill="#E0E0E0" />
          </svg>
      </a>
      {%  url 'cal:calendar_6months' as url_6months %}
      <a class="view-type" href="{% url 'cal:calendar_6months' %}">
          <svg width="50" height="50" viewBox="0 0 50 50" fill="none" xmlns="http://www.w3.org/2000/svg" {% if request.path == url_6months %} class="active" {% endif %}>
              <path fill-rule="evenodd" clip-rule="evenodd" d="M7 40.0001H17.4167V26.3638H7V40.0001ZM19.5 40.0001H29.9167V26.3638H19.5V40.0001ZM32 40.0001V26.3638H42.4167V40.0001H32Z" fill="#E0E0E0" />
              <path fill-rule="evenodd" clip-rule="evenodd" d="M7 23.6363H17.4167V10H7V23.6363ZM19.5 23.6363H29.9167V10H19.5V23.6363ZM32 23.6363V10H42.4167V23.6363H32Z" fill="#E0E0E0" />
          </svg>
      </a>
      {%  url 'cal:calendar' as url_calendar %}
      <a class="view-type" href="{% url 'cal:calendar' %}">
          <svg width="50" height="50" viewBox="0 0 50 50" fill="none" xmlns="http://www.w3.org/2000/svg" {% if request.path == url_calendar %} class="active" {% endif %}>
              <path fill-rule="evenodd" clip-rule="evenodd" d="M23.3693 18.7498H15.8096V10.4165H23.3693V18.7498ZM13.8098 18.7499H6.25V10.4166H13.8098V18.7499ZM25.3691 18.7498H32.9289V10.4165H25.3691V18.7498ZM42.4885 18.7498H34.9287V10.4165H42.4885V18.7498Z" fill="#E0E0E0" />
              <path fill-rule="evenodd" clip-rule="evenodd" d="M23.3693 29.1666H15.8096V20.8333H23.3693V29.1666ZM13.8098 29.1667H6.25V20.8333H13.8098V29.1667ZM25.3691 29.1666H32.9289V20.8333H25.3691V29.1666ZM42.4885 29.1666H34.9287V20.8333H42.4885V29.1666Z" fill="#E0E0E0" />
              <path fill-rule="evenodd" clip-rule="evenodd" d="M23.3693 39.5833H15.8096V31.25H23.3693V39.5833ZM13.8098 39.5834H6.25V31.2501H13.8098V39.5834ZM25.3691 39.5833H32.9289V31.25H25.3691V39.5833ZM42.4885 39.5833H34.9287V31.25H42.4885V39.5833Z" fill="#E0E0E0" />
          </svg>
      </a>
      {%  url 'cal:profile_edit' as url_profile %}
    </div>
    <div id="config">
        <svg width="50" height="50" viewBox="0 0 50 50" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M40.6249 25.0001C40.6249 25.7084 40.5624 26.3751 40.4791 27.0417L44.8749 30.4792C45.2707 30.7917 45.3749 31.3543 45.1249 31.8126L40.9582 39.0209C40.7082 39.4792 40.1666 39.6668 39.6874 39.4793L34.4999 37.3959C33.4166 38.2084 32.2499 38.9168 30.9791 39.4376L30.1874 44.9584C30.1249 45.4584 29.6874 45.8334 29.1666 45.8334H20.8332C20.3124 45.8334 19.8749 45.4584 19.8124 44.9584L19.0207 39.4376C17.7499 38.9168 16.5832 38.2293 15.4999 37.3959L10.3124 39.4793C9.85408 39.6459 9.29158 39.4792 9.04158 39.0209L4.87491 31.8126C4.62491 31.3543 4.72908 30.7917 5.12491 30.4792L9.52074 27.0417C9.43741 26.3751 9.37491 25.6876 9.37491 25.0001C9.37491 24.3126 9.43741 23.6251 9.52074 22.9584L5.12491 19.5209C4.72908 19.2084 4.60408 18.6459 4.87491 18.1876L9.04158 10.9792C9.29158 10.5209 9.83324 10.3334 10.3124 10.5209L15.4999 12.6042C16.5832 11.7917 17.7499 11.0834 19.0207 10.5626L19.8124 5.04175C19.8749 4.54175 20.3124 4.16675 20.8332 4.16675H29.1666C29.6874 4.16675 30.1249 4.54175 30.1874 5.04175L30.9791 10.5626C32.2499 11.0834 33.4166 11.7709 34.4999 12.6042L39.6874 10.5209C40.1457 10.3542 40.7082 10.5209 40.9582 10.9792L45.1249 18.1876C45.3749 18.6459 45.2707 19.2084 44.8749 19.5209L40.4791 22.9584C40.5624 23.6251 40.6249 24.2917 40.6249 25.0001ZM17.7084 25.0001C17.7084 29.0209 20.9792 32.2917 25.0001 32.2917C29.0209 32.2917 32.2917 29.0209 32.2917 25.0001C32.2917 20.9792 29.0209 17.7084 25.0001 17.7084C20.9792 17.7084 17.7084 20.9792 17.7084 25.0001Z" fill="#E0E0E0" />
        </svg>
        <div class="config-modal-form">
            <h5 class="config-title">Настройки</h5>
            <form class="profile_form" method="post" action="/profile/">
                {% csrf_token %}
                {{ profile }}
                <button class="btn-submit" type="submit" >Применить</button>
            </form>
        </div>
    </div>
      <!-- <a href="{% url 'logout'%}">Выйти</a> -->
</header>